src/Octava/Bundle/AdminMenuBundle/Form/Type/EntityType.php
<?php
namespace Octava\Bundle\AdminMenuBundle\Form\Type;

use Octava\Bundle\AdminMenuBundle\AdminMenuManager;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormInterface;
use Symfony\Component\Form\FormView;
use Symfony\Component\OptionsResolver\OptionsResolver;

class EntityType extends AbstractType
{
    const TYPE_NAME = 'octava_admin_menu_entity';

    /**
     * @var AdminMenuManager
     */
    protected $menuManager;

    public function __construct(AdminMenuManager $menuManager)
    {
        $this->menuManager = $menuManager;
    }

    /**
     * @return AdminMenuManager
     */
    public function getMenuManager()
    {
        return $this->menuManager;
    }

    /**
     * Returns the name of this type.
     *
     * @return string The name of this type
     */
    public function getName()
    {
        return self::TYPE_NAME;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(
            [
                'tree_list' => $this->getMenuManager()->getFolderChoices(),
                'excluded_ids' => [],
                'default_data' => null,
            ]
        );
    }

    public function buildView(FormView $view, FormInterface $form, array $options)
    {
        $view->vars['tree_list'] = $options['tree_list'];
        $view->vars['excluded_ids'] = $options['excluded_ids'];
        $view->vars['default_data'] = $options['default_data'];
    }

    public function getParent()
    {
        return 'entity';
    }
}

src/Octava/Bundle/AdminMenuBundle/Resources/views/CRUD/admin_menu_edit.html.twig
{% extends 'OctavaAdminBundle:CRUD:edit.html.twig' %}

{% form_theme form.parent 'OctavaAdminMenuBundle:Form:octava_admin_menu_entity_widget.html.twig' %}

src/Octava/Bundle/AdminMenuBundle/Resources/views/CRUD/admin_menu_list.html.twig
{% extends 'OctavaAdminBundle:CRUD:list.html.twig' %}

{% block table_body %}
    <tbody data-no-turbolink>
    {% for object in admin.getMenuTree() %}
        <tr id="row_{{ object.id }}">
            {% include admin.getTemplate('inner_list_row') %}
        </tr>
    {% endfor %}
    </tbody>
{% endblock %}

{#{% block side_bar_before_nav %}#}
    {#<div>#}
        {#{{ admin.getTreeManager().get|raw }}#}
    {#</div>#}
{#{% endblock %}#}

{% block list_footer '' %}
{#{% block pager_links '' %}#}

src/Octava/Bundle/AdminMenuBundle/Resources/views/CRUD/admin_menu_list__action_create.html.twig
{% if admin.isGranted('CREATE', object) and admin.hasRoute('create') and object.type == 'folder' %}
    <a class="btn btn-sm btn-default add_link"
       href="{{ admin.generateUrl('create') }}">
        <i class="fa fa-plus-circle"></i>
        {{ 'link_action_create'|trans({}, 'SonataAdminBundle') }}</a>
{% endif %}

src/Octava/Bundle/AdminMenuBundle/Resources/views/CRUD/admin_menu_list_title_field.html.twig
<td style="padding-left: {{ (object.level+1) * 30 }}px;{{ object.type == constant('TYPE_FOLDER', object) ? 'font-weight:bold' : '' }}">
    {{ object.type == constant('TYPE_FOLDER', object) ? '<i class="fa fa-folder-open-o"></i>' : '' }} {{ value }}
</td>